<?php
$labels = array();
$labels['quota_plugin_title'] = 'حصة صندوق البريد';
$labels['quotasettings'] = 'حصة صندوق البريد';
$labels['chart_title'] = 'مخطط حصص صندوق البريد';
$labels['space_used'] = 'حصة صندوق البريد المستخدمة';
$labels['space_free'] = 'حصة صندوق البريد مجاناً';
$labels['quota_meet_90'] = 'لقد استخدمت أكثر من 90% من حصة التخزين الخاصة بك.';
$labels['quota_meet_99'] = 'لقد استخدمت أكثر من 99% من حصة التخزين الخاصة بك.';
$labels['problem_please_contact'] = 'إذا كانت لديك أي مشاكل، يُرجى الاتصال بـ %s.';
$labels['unknown'] = 'غير معروف';
?>
