<?php
$labels = array();
$labels['quota_plugin_title'] = 'Квота на пощенската кутия';
$labels['quotasettings'] = 'Квота на пощенската кутия';
$labels['chart_title'] = 'Диаграма на квотите за пощенски кутии';
$labels['space_used'] = 'Използвана квота за пощенски кутии';
$labels['space_free'] = 'Безплатна квота на пощенската кутия';
$labels['quota_meet_90'] = 'Използвали сте над 90% от квотата си за съхранение.';
$labels['quota_meet_99'] = 'Използвали сте над 99% от квотата си за съхранение.';
$labels['problem_please_contact'] = 'Ако имате някакви проблеми, моля, свържете се с %s.';
$labels['unknown'] = 'неизвестен';
?>
