<?php
$labels = array();
$labels['quota_plugin_title'] = 'Kvóta poštovních schránek';
$labels['chart_title'] = 'Graf kvót poštovních schránek';
$labels['space_used'] = 'Použitá kvóta poštovních schránek';
$labels['space_free'] = 'Kvóta poštovních schránek zdarma';
$labels['quota_meet_90'] = 'Využili jste více než 90 % své kvóty úložiště.';
$labels['quota_meet_99'] = 'Využili jste více než 99 % své kvóty úložiště.';
$labels['problem_please_contact'] = 'V případě jakýchkoli problémů se obraťte na %s.';
$labels['unknown'] = 'neznámý';
?>
