<?php
$labels = array();
$labels['quota_plugin_title'] = 'Kvote for postkasse';
$labels['quotasettings'] = 'Kvote for postkasse';
$labels['chart_title'] = 'Oversigt over postkasse-kvoter';
$labels['space_used'] = 'Anvendt postkassekvote';
$labels['space_free'] = 'Kvotefri postkasse';
$labels['quota_meet_90'] = 'Du har brugt over 90% af din lagerkvote.';
$labels['quota_meet_99'] = 'Du har brugt over 99% af din lagerkvote.';
$labels['problem_please_contact'] = 'Hvis du har problemer, bedes du kontakte %s.';
$labels['unknown'] = 'ukendt';
?>
