<?php
$labels = array();
$labels['quota_plugin_title'] = 'Mailbox-Kontingent';
$labels['quotasettings'] = 'Mailbox-Kontingent';
$labels['chart_title'] = 'Mailbox-Quotentabelle';
$labels['space_used'] = 'Mailbox-Kontingent verwendet';
$labels['space_free'] = 'Mailbox-Kontingent Frei';
$labels['quota_meet_90'] = 'Sie haben über 90% Ihres Speicherkontingents verbraucht.';
$labels['quota_meet_99'] = 'Sie haben Ihr Speicherkontingent zu über 99 % ausgeschöpft.';
$labels['problem_please_contact'] = 'Wenn Sie Probleme haben, wenden Sie sich bitte an %s.';
$labels['unknown'] = 'unbekannt';
?>
