<?php
$labels = array();
$labels['quota_plugin_title'] = 'Cuota de buzones';
$labels['quotasettings'] = 'Cuota de buzones';
$labels['chart_title'] = 'Cuadro de cuotas de buzones';
$labels['space_used'] = 'Cuota de buzones utilizada';
$labels['space_free'] = 'Cuota de buzones gratuita';
$labels['quota_meet_90'] = 'Has utilizado más del 90% de tu cuota de almacenamiento.';
$labels['quota_meet_99'] = 'Has utilizado más del 99% de tu cuota de almacenamiento.';
$labels['problem_please_contact'] = 'Si tiene algún problema, póngase en contacto con %s.';
$labels['unknown'] = 'desconocido';
?>
