<?php
$labels = array();
$labels['quota_plugin_title'] = 'Postkasti kvoot';
$labels['quotasettings'] = 'Postkasti kvoot';
$labels['chart_title'] = 'Postkastide kvootide tabel';
$labels['space_used'] = 'Kasutatud postkasti kvoot';
$labels['space_free'] = 'Postkasti kvoot tasuta';
$labels['quota_meet_90'] = 'Olete kasutanud üle 90% oma mälukvoodist.';
$labels['quota_meet_99'] = 'Olete kasutanud üle 99% oma mälukvoodist.';
$labels['problem_please_contact'] = 'Kui teil on mingeid probleeme, võtke palun ühendust %s.';
$labels['unknown'] = 'unknown';
?>
