<?php
$labels = array();
$labels['quota_plugin_title'] = 'Postilaatikon kiintiö';
$labels['chart_title'] = 'Postilaatikon kiintiökaavio';
$labels['space_used'] = 'Käytetty postilaatikkokiintiö';
$labels['space_free'] = 'Postilaatikon kiintiö ilmaiseksi';
$labels['quota_meet_90'] = 'Olet käyttänyt yli 90 % tallennuskiintiöstäsi.';
$labels['quota_meet_99'] = 'Olet käyttänyt yli 99 % tallennuskiintiöstäsi.';
$labels['problem_please_contact'] = 'Jos sinulla on ongelmia, ota yhteyttä %s.';
$labels['unknown'] = 'tuntematon';
?>
