<?php
$labels = array();
$labels['quota_plugin_title'] = 'Quota de boîte aux lettres';
$labels['quotasettings'] = 'Quota de boîte aux lettres';
$labels['chart_title'] = 'Tableau des quotas de boîtes aux lettres';
$labels['space_used'] = 'Quota de boîte aux lettres utilisé';
$labels['space_free'] = 'Quota de boîte aux lettres gratuit';
$labels['quota_meet_90'] = 'Vous avez utilisé plus de 90 % de votre quota de stockage.';
$labels['quota_meet_99'] = 'Vous avez utilisé plus de 99 % de votre quota de stockage.';
$labels['problem_please_contact'] = 'Si vous avez des problèmes, veuillez contacter %s.';
$labels['unknown'] = 'inconnue';
?>
