<?php
$labels = array();
$labels['quota_plugin_title'] = 'מכסת תיבת דואר';
$labels['quotasettings'] = 'מכסת תיבת דואר';
$labels['chart_title'] = 'תרשים מכסת תיבות דואר';
$labels['space_used'] = 'מכסת תיבת הדואר המשומשת';
$labels['space_free'] = 'מכסת תיבת דואר חינם';
$labels['quota_meet_90'] = 'השתמשת ביותר מ-90% ממכסת האחסון שלך.';
$labels['quota_meet_99'] = 'השתמשת ביותר מ-99% ממכסת האחסון שלך.';
$labels['problem_please_contact'] = 'אם יש לך בעיות, אנא פנה ל- %s.';
$labels['unknown'] = 'לא ידוע';
?>
