<?php
$labels = array();
$labels['quota_plugin_title'] = 'Postafiók kvóta';
$labels['chart_title'] = 'Postafiók-kvóta táblázat';
$labels['space_used'] = 'Használt postafiók kvóta';
$labels['space_free'] = 'Mailbox kvóta ingyenes';
$labels['quota_meet_90'] = 'A tárolási kvótájának több mint 90%-át felhasználta.';
$labels['quota_meet_99'] = 'A tárolási kvótájának több mint 99%-át felhasználta.';
$labels['problem_please_contact'] = 'Ha bármilyen problémája van, kérjük, lépjen kapcsolatba %s.';
$labels['unknown'] = 'unknown';
?>
