<?php
$labels = array();
$labels['quota_plugin_title'] = 'Kuota Kotak Surat';
$labels['chart_title'] = 'Bagan Kuota Kotak Surat';
$labels['space_used'] = 'Kuota Kotak Surat yang Digunakan';
$labels['space_free'] = 'Gratis Kuota Kotak Surat';
$labels['quota_meet_90'] = 'Anda telah menggunakan lebih dari 90% kuota penyimpanan Anda.';
$labels['quota_meet_99'] = 'Anda telah menggunakan lebih dari 99% kuota penyimpanan Anda.';
$labels['problem_please_contact'] = 'Jika Anda memiliki masalah, silakan hubungi %s.';
$labels['unknown'] = 'tidak diketahui';
?>
