<?php
$labels = array();
$labels['quota_plugin_title'] = 'Quota della casella di posta';
$labels['chart_title'] = 'Tabella delle quote delle caselle di posta';
$labels['space_used'] = 'Quota casella di posta utilizzata';
$labels['space_free'] = 'Quota della casella di posta elettronica gratuita';
$labels['quota_meet_90'] = 'È stato utilizzato oltre il 90% della quota di archiviazione.';
$labels['quota_meet_99'] = 'È stato utilizzato oltre il 99% della quota di archiviazione.';
$labels['problem_please_contact'] = 'In caso di problemi, contattare %s.';
$labels['unknown'] = 'sconosciuto';
?>
