<?php
$labels = array();
$labels['quota_plugin_title'] = 'メールボックス・クォータ';
$labels['chart_title'] = 'メールボックス割り当て表';
$labels['space_used'] = '使用メールボックス・クォータ';
$labels['space_free'] = 'メールボックス・クォータ・フリー';
$labels['quota_meet_90'] = 'ストレージクォータの90%以上を使用しています。';
$labels['quota_meet_99'] = 'ストレージクォータの99%以上を使用しています。';
$labels['problem_please_contact'] = '何か問題がありましたら、%sまでご連絡ください。';
$labels['unknown'] = '不明';
?>
