<?php
$labels = array();
$labels['quota_plugin_title'] = '사서함 할당량';
$labels['quotasettings'] = '사서함 할당량';
$labels['chart_title'] = '사서함 할당량 차트';
$labels['space_used'] = '사서함 할당량 사용';
$labels['space_free'] = '사서함 할당량 무료';
$labels['quota_meet_90'] = '스토리지 할당량의 90% 이상을 사용했습니다.';
$labels['quota_meet_99'] = '스토리지 할당량의 99% 이상을 사용했습니다.';
$labels['problem_please_contact'] = '문제가 있는 경우 %s에 문의하세요.';
$labels['unknown'] = '알 수 없음';
?>
