<?php
$labels = array();
$labels['quota_plugin_title'] = 'Pašto dėžučių kvota';
$labels['chart_title'] = 'Pašto dėžučių kvotų diagrama';
$labels['space_used'] = 'Naudojama pašto dėžučių kvota';
$labels['space_free'] = 'Pašto dėžutės kvota nemokamai';
$labels['quota_meet_90'] = 'Panaudojote daugiau kaip 90 % savo saugyklos kvotos.';
$labels['quota_meet_99'] = 'Panaudojote daugiau kaip 99 % savo saugyklos kvotos.';
$labels['problem_please_contact'] = 'Jei turite kokių nors problemų, kreipkitės į %s.';
$labels['unknown'] = 'nežinomas';
?>
