<?php
$labels = array();
$labels['quota_plugin_title'] = 'Pasta kastītes kvota';
$labels['quotasettings'] = 'Pasta kastītes kvota';
$labels['chart_title'] = 'Pastkastītes kvotas diagramma';
$labels['space_used'] = 'Izmantotā pastkastes kvota';
$labels['space_free'] = 'Pasta kastītes kvota bez maksas';
$labels['quota_meet_90'] = 'Jūs esat izmantojis vairāk nekā 90 % no savas glabāšanas kvotas.';
$labels['quota_meet_99'] = 'Jūs esat izmantojis vairāk nekā 99 % no savas glabāšanas kvotas.';
$labels['problem_please_contact'] = 'Ja rodas problēmas, lūdzu, sazinieties ar %s.';
$labels['unknown'] = 'nezināms';
?>
