<?php
$labels = array();
$labels['quota_plugin_title'] = 'Mailbox quota';
$labels['quotasettings'] = 'Mailbox quota';
$labels['chart_title'] = 'Overzicht mailbox quota';
$labels['space_used'] = 'Gebruikt mailbox quotum';
$labels['space_free'] = 'Mailbox quotum gratis';
$labels['quota_meet_90'] = 'Je hebt meer dan 90% van je opslagquota gebruikt.';
$labels['quota_meet_99'] = 'Je hebt meer dan 99% van je opslagquota gebruikt.';
$labels['problem_please_contact'] = 'Als je problemen hebt, neem dan contact op met %s.';
$labels['unknown'] = 'onbekend';
?>
