<?php
$labels = array();
$labels['quota_plugin_title'] = 'Postkassekvote';
$labels['chart_title'] = 'Diagram over postkassekvoter';
$labels['space_used'] = 'Brukt postkassekvote';
$labels['space_free'] = 'Kvotefri postkasse';
$labels['quota_meet_90'] = 'Du har brukt over 90 % av lagringskvoten din.';
$labels['quota_meet_99'] = 'Du har brukt over 99 % av lagringskvoten din.';
$labels['problem_please_contact'] = 'Hvis du har noen problemer, kan du kontakte %s.';
$labels['unknown'] = 'ukjent';
?>
