<?php
$labels = array();
$labels['quota_plugin_title'] = 'Limit skrzynki pocztowej';
$labels['quotasettings'] = 'Limit skrzynki pocztowej';
$labels['chart_title'] = 'Tabela limitów skrzynek pocztowych';
$labels['space_used'] = 'Wykorzystany limit skrzynki pocztowej';
$labels['space_free'] = 'Wolny limit skrzynki pocztowej';
$labels['quota_meet_90'] = 'Wykorzystano ponad 90% limitu miejsca.';
$labels['quota_meet_99'] = 'Wykorzystano ponad 99% limitu miejsca.';
$labels['problem_please_contact'] = 'W razie jakichkolwiek problemów prosimy o kontakt z %s.';
$labels['unknown'] = 'nieznany';
?>
