<?php
$labels = array();
$labels['quota_plugin_title'] = 'Cota de caixa de correio';
$labels['quotasettings'] = 'Cota de caixa de correio';
$labels['chart_title'] = 'Gráfico de cota de caixa de correio';
$labels['space_used'] = 'Cota de caixa de correio usada';
$labels['space_free'] = 'Cota de caixa de correio gratuita';
$labels['quota_meet_90'] = 'Você usou mais de 90% da sua cota de armazenamento.';
$labels['quota_meet_99'] = 'Você usou mais de 99% da sua cota de armazenamento.';
$labels['problem_please_contact'] = 'Se tiver algum problema, entre em contato com %s.';
$labels['unknown'] = 'desconhecido';
?>
