<?php
$labels = array();
$labels['quota_plugin_title'] = 'Cota căsuței poștale';
$labels['chart_title'] = 'Tabel cote căsuță poștală';
$labels['space_used'] = 'Cota căsuței poștale utilizată';
$labels['space_free'] = 'Cota de căsuță poștală gratuită';
$labels['quota_meet_90'] = 'Ați utilizat peste 90% din cota dvs. de stocare.';
$labels['quota_meet_99'] = 'Ați utilizat peste 99% din cota dvs. de stocare.';
$labels['problem_please_contact'] = 'Dacă aveți probleme, vă rugăm să contactați %s.';
$labels['unknown'] = 'necunoscut';
?>
