<?php
$labels = array();
$labels['quota_plugin_title'] = 'Квота почтовых ящиков';
$labels['chart_title'] = 'Диаграмма квот почтовых ящиков';
$labels['space_used'] = 'Используемая квота почтовых ящиков';
$labels['space_free'] = 'Квота почтового ящика бесплатно';
$labels['quota_meet_90'] = 'Вы использовали более 90 % квоты на хранение.';
$labels['quota_meet_99'] = 'Вы использовали более 99 % квоты на хранение.';
$labels['problem_please_contact'] = 'Если у вас возникнут какие-либо проблемы, свяжитесь с %s.';
$labels['unknown'] = 'неизвестно';
?>
