<?php
$labels = array();
$labels['quota_plugin_title'] = 'Kvóta poštových schránok';
$labels['chart_title'] = 'Graf kvót poštových schránok';
$labels['space_used'] = 'Použitá kvóta poštových schránok';
$labels['space_free'] = 'Kvóta poštových schránok zadarmo';
$labels['quota_meet_90'] = 'Využili ste viac ako 90 % svojej kvóty úložiska.';
$labels['quota_meet_99'] = 'Využili ste viac ako 99 % svojej kvóty úložiska.';
$labels['problem_please_contact'] = 'V prípade akýchkoľvek problémov kontaktujte %s.';
$labels['unknown'] = 'neznáme';
?>
