<?php
$labels = array();
$labels['quota_plugin_title'] = 'Kvota poštnih predalov';
$labels['chart_title'] = 'Diagram kvote poštnih predalov';
$labels['space_used'] = 'Uporabljena kvota poštnih predalov';
$labels['space_free'] = 'Kvota poštnega predala brezplačno';
$labels['quota_meet_90'] = 'Porabili ste več kot 90 % kvote za shranjevanje.';
$labels['quota_meet_99'] = 'Porabili ste več kot 99 % kvote za shranjevanje.';
$labels['problem_please_contact'] = 'Če imate težave, se obrnite na %s.';
$labels['unknown'] = 'neznano';
?>
