<?php
$labels = array();
$labels['quota_plugin_title'] = 'Kvot för brevlåda';
$labels['chart_title'] = 'Kvotdiagram för brevlåda';
$labels['space_used'] = 'Använd kvot för brevlåda';
$labels['space_free'] = 'Kvot för brevlåda gratis';
$labels['quota_meet_90'] = 'Du har använt mer än 90 % av din lagringskvot.';
$labels['quota_meet_99'] = 'Du har använt mer än 99 % av din lagringskvot.';
$labels['problem_please_contact'] = 'Om du har några problem, vänligen kontakta %s.';
$labels['unknown'] = 'okänd';
?>
