<?php
$labels = array();
$labels['quota_plugin_title'] = 'Posta Kutusu Kotası';
$labels['quotasettings'] = 'Posta Kutusu Kotası';
$labels['chart_title'] = 'Posta Kutusu Kota Tablosu';
$labels['space_used'] = 'Kullanılan Posta Kutusu Kotası';
$labels['space_free'] = 'Posta Kutusu Kotası Ücretsiz';
$labels['quota_meet_90'] = 'Depolama kotanızın %90\'ından fazlasını kullandınız.';
$labels['quota_meet_99'] = 'Depolama kotanızın %99\'undan fazlasını kullandınız.';
$labels['problem_please_contact'] = 'Herhangi bir sorununuz varsa, lütfen %s ile iletişime geçin.';
$labels['unknown'] = 'bilinmiyor';
?>
