<?php
$labels = array();
$labels['quota_plugin_title'] = 'Квота поштової скриньки';
$labels['quotasettings'] = 'Квота поштової скриньки';
$labels['chart_title'] = 'Таблиця квот поштових скриньок';
$labels['space_used'] = 'Використано квоту поштової скриньки';
$labels['space_free'] = 'Поштова скринька без квоти';
$labels['quota_meet_90'] = 'Ви використали понад 90% своєї квоти на зберігання.';
$labels['quota_meet_99'] = 'Ви використали понад 99% своєї квоти на зберігання.';
$labels['problem_please_contact'] = 'Якщо у вас виникли проблеми, будь ласка, зв\'яжіться з %s.';
$labels['unknown'] = 'невідомо';
?>
