<?php
$labels = array();
$labels['quota_plugin_title'] = 'Giới hạn dung lượng hộp thư';
$labels['quotasettings'] = 'Giới hạn dung lượng hộp thư';
$labels['chart_title'] = 'Biểu đồ giới hạn dung lượng hộp thư';
$labels['space_used'] = 'Dung lượng hộp thư đã sử dụng';
$labels['space_free'] = 'Dung lượng hộp thư miễn phí';
$labels['quota_meet_90'] = 'Bạn đã sử dụng hơn 90% dung lượng lưu trữ của mình.';
$labels['quota_meet_99'] = 'Bạn đã sử dụng hơn 99% dung lượng lưu trữ của mình.';
$labels['problem_please_contact'] = 'Nếu bạn gặp bất kỳ vấn đề nào, vui lòng liên hệ với %s.';
$labels['unknown'] = 'không rõ';
?>
